blank_issues_enabled: false
contact_links:
  - name: Vraag
    url: https://github.com/itsdarklikehell/RetroPie-Stream-Recording/discussions
    about: Stel vragen en bediskussieer met andere gebruikers
